// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod serein {
        pub mod adapter {
            /// Zero-Trust WASM Adapter interface for LLM API authentication isolation.
            ///
            /// Decouples provider-specific authentication mechanisms (IAM signing,
            /// non-standard headers, token refresh) from the core TMR consensus engine.
            /// Each provider with a non-OpenAI-compatible auth scheme gets its own
            /// `.wasm` plugin implementing this contract, hot-swappable at runtime.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod api_adapter {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Canonical request from the TMR engine, normalized across all providers.
                #[derive(Clone)]
                pub struct StandardizedRequest {
                    pub model: _rt::String,
                    pub prompt: _rt::String,
                    pub temperature: f32,
                    pub base_url: _rt::String,
                }
                impl ::core::fmt::Debug for StandardizedRequest {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("StandardizedRequest")
                            .field("model", &self.model)
                            .field("prompt", &self.prompt)
                            .field("temperature", &self.temperature)
                            .field("base-url", &self.base_url)
                            .finish()
                    }
                }
                /// HTTP request specification produced by the adapter for host-side execution.
                ///
                /// The host (Serein microkernel) performs the actual HTTP I/O using its own
                /// reqwest client pool. The adapter only produces the spec - it never touches
                /// the network directly. This enforces capability-based security: WASM plugins
                /// cannot open sockets, only produce data for the host to act upon.
                #[derive(Clone)]
                pub struct HttpRequestSpec {
                    pub url: _rt::String,
                    /// List of (header-name, header-value) pairs.
                    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                    pub body: _rt::String,
                }
                impl ::core::fmt::Debug for HttpRequestSpec {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("HttpRequestSpec")
                            .field("url", &self.url)
                            .field("headers", &self.headers)
                            .field("body", &self.body)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_transform_request_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: f32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    let len3 = arg8;
                    let bytes3 = _rt::Vec::from_raw_parts(arg7.cast(), len3, len3);
                    let result4 = T::transform_request(
                        StandardizedRequest {
                            model: _rt::string_lift(bytes0),
                            prompt: _rt::string_lift(bytes1),
                            temperature: arg4,
                            base_url: _rt::string_lift(bytes2),
                        },
                        _rt::string_lift(bytes3),
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let HttpRequestSpec {
                                url: url6,
                                headers: headers6,
                                body: body6,
                            } = e;
                            let vec7 = (url6.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                            let vec11 = headers6;
                            let len11 = vec11.len();
                            let layout11 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec11.len() * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result11 = if layout11.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout11).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout11);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec11.into_iter().enumerate() {
                                let base = result11
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let (t8_0, t8_1) = e;
                                    let vec9 = (t8_0.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base.add(0).cast::<*mut u8>() = ptr9.cast_mut();
                                    let vec10 = (t8_1.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                            }
                            *ptr5
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr5
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result11;
                            let vec12 = (body6.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr5
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr5
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec13 = (e.into_bytes()).into_boxed_slice();
                            let ptr13 = vec13.as_ptr().cast::<u8>();
                            let len13 = vec13.len();
                            ::core::mem::forget(vec13);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len13;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr13.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_transform_request<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base9 = l3;
                            let len9 = l4;
                            for i in 0..len9 {
                                let base = base9
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l5 = *base.add(0).cast::<*mut u8>();
                                    let l6 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                    let l7 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base9,
                                len9 * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l10 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l11 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                        }
                        _ => {
                            let l12 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_response_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse_response(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_parse_response<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Transform a canonical TMR request into a provider-specific HTTP request spec.
                    ///
                    /// The adapter receives the API key from the host (never stored in WASM memory
                    /// across invocations) and produces the complete HTTP request specification.
                    /// The host then executes the HTTP call and passes the raw response body to
                    /// `parse-response` for extraction.
                    fn transform_request(
                        req: StandardizedRequest,
                        api_key: _rt::String,
                    ) -> Result<HttpRequestSpec, _rt::String>;
                    /// Parse the raw HTTP response body into a canonical content string.
                    ///
                    /// Each provider returns a different JSON structure. The adapter normalizes
                    /// the response into a plain text content string that the TMR engine can
                    /// compare across providers for consensus arbitration.
                    fn parse_response(
                        raw_body: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_serein_adapter_api_adapter_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "serein:adapter/api-adapter@1.0.0#transform-request")] unsafe
                        extern "C" fn export_transform_request(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : f32, arg5 : * mut
                        u8, arg6 : usize, arg7 : * mut u8, arg8 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_transform_request_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "cabi_post_serein:adapter/api-adapter@1.0.0#transform-request")]
                        unsafe extern "C" fn _post_return_transform_request(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_transform_request::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "serein:adapter/api-adapter@1.0.0#parse-response")] unsafe extern
                        "C" fn export_parse_response(arg0 : * mut u8, arg1 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_parse_response_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_serein:adapter/api-adapter@1.0.0#parse-response")]
                        unsafe extern "C" fn _post_return_parse_response(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_parse_response::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_serein_adapter_api_adapter_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 7 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 7
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_adapter_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::serein::adapter::api_adapter::__export_serein_adapter_api_adapter_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::serein::adapter::api_adapter);
    };
}
#[doc(inline)]
pub(crate) use __export_adapter_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:serein:adapter@1.0.0:adapter-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 425] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa5\x02\x01A\x02\x01\
A\x02\x01B\x0c\x01r\x04\x05models\x06prompts\x0btemperaturev\x08base-urls\x04\0\x14\
standardized-request\x03\0\0\x01o\x02ss\x01p\x02\x01r\x03\x03urls\x07headers\x03\
\x04bodys\x04\0\x11http-request-spec\x03\0\x04\x01j\x01\x05\x01s\x01@\x02\x03req\
\x01\x07api-keys\0\x06\x04\0\x11transform-request\x01\x07\x01j\x01s\x01s\x01@\x01\
\x08raw-bodys\0\x08\x04\0\x0eparse-response\x01\x09\x04\0\x20serein:adapter/api-\
adapter@1.0.0\x05\0\x04\0\"serein:adapter/adapter-world@1.0.0\x04\0\x0b\x13\x01\0\
\x0dadapter-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compone\
nt\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
